"""empty message

Revision ID: 0b987a4a9441
Revises: 8740ed88ad7a
Create Date: 2025-04-27 02:59:46.030847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b987a4a9441'
down_revision = '8740ed88ad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_user_from_id_fkey', type_='foreignkey')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('follower_user_from_id_fkey', 'user', ['user_from_id'], ['id'])

    # ### end Alembic commands ###
