"""empty message

Revision ID: 8740ed88ad7a
Revises: a6ae70018978
Create Date: 2025-04-25 03:45:27.600273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8740ed88ad7a'
down_revision = 'a6ae70018978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['autor_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
